[package]
name = "klick-frontend"
version = "0.4.1"
edition = "2021"
publish = false
rust-version = "1.76"

[dependencies]
# Project dependencies
klick-app-api = "=0.0.0"
klick-app-charts = "=0.0.0"
klick-app-components = "=0.0.0"
klick-boundary = { version = "=0.0.0", features = ["conversion", "extra-derive"] }
klick-domain = { path = "../crates/domain" }
klick-presenter = "=0.0.0"

# External dependencies
chrono = "0.4"
anyhow = "1.0.81"
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
derive_more = "0.99.17"
gloo-file = { version = "0.3.0", features = ["futures"] }
gloo-storage = "0.3.0"
js-sys = "0.3.69"
leptos = { version = "0.6.9", features = ["csr"] }
leptos_meta = { version = "0.6.9", features = ["csr"] }
leptos_router = { version = "0.6.9", features = ["csr"] }
log = "0.4.21"
num-traits = "0.2.18"
pulldown-cmark = "0.10.0"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
strum = "0.26.2"
thiserror = "1.0.58"
time = { version = "0.3.34", features = ["macros", "formatting"] }

[patch.crates-io]
# Local paths to library crates in workspace
klick-app-api          = { path = "../crates/app-api"         }
klick-app-components   = { path = "../crates/app-components"  }
klick-app-charts       = { path = "../crates/app-charts"      }
klick-boundary         = { path = "../crates/boundary"        }
klick-domain           = { path = "../crates/domain"          }
klick-presenter        = { path = "../crates/presenter"       }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[lints.clippy]
pedantic = "warn"
missing_const_for_fn = "warn"

# The error types returned should be self-explanatory.
missing_errors_doc = "allow"

# Repetitions of module/type names occur frequently when using many
# modules for keeping the size of the source files handy. Often
# types have the same name as their parent module.
module_name_repetitions = "allow"

# This is a matter of taste... and I just like it that way ;-P
mod_module_files = "allow"

[build-dependencies]
toml = "0.8.11"
