[package]
name = "klick-frontend"
version = "0.1.3"
edition = "2021"
publish = false
rust-version = "1.74.0"

[dependencies]
# Project dependencies
klick-application = "=0.0.0"
klick-boundary = { version = "=0.0.0", features = ["conversion"] }
klick-svg-charts = "=0.0.0"

# External dependencies
anyhow = "1.0.75"
charming = { version = "0.2.5", features = ["wasm"] }
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
gloo-file = { version = "0.3.0", features = ["futures"] }
Inflector = "0.11.4"
leptos = { version = "0.5.2", features = ["csr"] }
leptos_meta = { version = "0.5.2", features = ["csr"] }
leptos_router = { version = "0.5.2", features = ["csr"] }
log = "0.4.20"
pulldown-cmark = "0.9.3"
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
strum = "0.25.0"
thiserror = "1.0.50"

[patch.crates-io]
# Local paths to library crates in workspace
klick-application = { path = "../application" }
klick-boundary    = { path = "../boundary"    }
klick-svg-charts  = { path = "../svg-charts"  }

[patch.crates-io.charming]
git = "https://github.com/qknight/charming"
branch = "klick_builder_pattern"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[lints.clippy]
pedantic = "warn"
missing_const_for_fn = "warn"

# The error types returned should be self-explanatory.
missing_errors_doc = "allow"

# Repetitions of module/type names occur frequently when using many
# modules for keeping the size of the source files handy. Often
# types have the same name as their parent module.
module_name_repetitions = "allow"

# This is a matter of taste... and I just like it that way ;-P
mod_module_files = "allow"

[build-dependencies]
toml = "0.8.8"
