[package]
name = "klick-frontend"
version = "0.3.5"
edition = "2021"
publish = false
rust-version = "1.75"

[dependencies]
# Project dependencies
klick-application = "=0.0.0"
klick-boundary = { version = "=0.0.0", features = ["conversion", "extra-derive"] }
klick-domain = "=0.0.0"
klick-format-numbers = "=0.0.0"
klick-svg-charts = "=0.0.0"

# External dependencies
anyhow = "1.0.79"
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
gloo-file = { version = "0.3.0", features = ["futures"] }
gloo-net = { version = "0.5.0", default-features = false, features = ["http", "json"] }
gloo-storage = "0.3.0"
Inflector = "0.11.4"
js-sys = "0.3.67"
leptos = { version = "0.6.3", features = ["csr"] }
leptos_meta = { version = "0.6.3", features = ["csr"] }
leptos_router = { version = "0.6.3", features = ["csr"] }
log = "0.4.20"
pulldown-cmark = "0.9.4"
serde_json = "1.0.112"
serde = { version = "1.0.196", features = ["derive"] }
strum = "0.25.0"
thiserror = "1.0.56"
time = { version = "0.3.31", features = ["macros", "formatting"] }

[patch.crates-io]
# Local paths to library crates in workspace
klick-application      = { path = "../crates/application"     }
klick-boundary         = { path = "../crates/boundary"        }
klick-domain           = { path = "../crates/domain"          }
klick-format-numbers   = { path = "../crates/format-numbers"  }
klick-svg-charts       = { path = "../crates/svg-charts"      }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[lints.clippy]
pedantic = "warn"
missing_const_for_fn = "warn"

# The error types returned should be self-explanatory.
missing_errors_doc = "allow"

# Repetitions of module/type names occur frequently when using many
# modules for keeping the size of the source files handy. Often
# types have the same name as their parent module.
module_name_repetitions = "allow"

# This is a matter of taste... and I just like it that way ;-P
mod_module_files = "allow"

[build-dependencies]
toml = "0.8.8"
