[package]
name = "klick-frontend"
version = "0.0.0"
edition = "2021"
publish = false
rust-version = "1.72.1"

[dependencies]
# Project dependencies
klick-boundary = "=0.0.0"

# External dependencies
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
leptos = { version = "0.5.0-rc3", features = ["csr"] }
log = "0.4.20"

[patch.crates-io]
# Local paths to library crates in workspace
klick-boundary = { path = "../boundary" }
