[package]
name = "klick-frontend"
version = "0.0.0"
edition = "2021"
publish = false
rust-version = "1.73.0"

[dependencies]
# Project dependencies
klick-application = "=0.0.0"
klick-boundary = { version = "=0.0.0", features = ["conversion"] }
klick-svg-charts = "=0.0.0"

# External dependencies
charming = { version = "0.2.5", features = ["wasm"] }
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
Inflector = "0.11.4"
leptos = { version = "0.5.1", features = ["csr"] }
leptos_meta = { version = "0.5.1", features = ["csr"] }
leptos_router = { version = "0.5.1", features = ["csr"] }
log = "0.4.20"
pulldown-cmark = "0.9.3"
strum = "0.25.0"
thiserror = "1.0.49"
serde_json = "1.0.108"

[patch.crates-io]
# Local paths to library crates in workspace
klick-application = { path = "../application" }
klick-boundary    = { path = "../boundary"    }
klick-svg-charts  = { path = "../svg-charts"  }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
