[package]
name = "klick-app-charts"
version = "0.0.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
klick-presenter = "=0.0.0"

leptos = "0.6.6"
log = "0.4.20"

[features]
ssr = []

[lints]
workspace = true
