[package]
name = "klick-format-numbers"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]

[lints]
workspace = true
