[package]
name = "sankey-example"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
klick-app-charts = { path = "../.." }

console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = { version = "0.6.6", features = ["csr"] }
log = "0.4.20"
