[package]
name = "klick-svg-charts"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
klick-format-numbers = "=0.0.0"

leptos = "0.5.7"
log = "0.4.20"

[features]
ssr = []

[lints]
workspace = true
