[package]
name = "klick-value-spec-proc-macro"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
itertools = "0.13.0"
quote = "1.0.37"
syn = { version = "2.0", features = ["full"] }
