use crate::units::Tons;

#[derive(Debug, Clone)]
pub struct CO2Equivalents {
    pub n2o_plant: Tons,
    pub n2o_water: Tons,
    pub n2o_side_stream: Tons,
    pub n2o_emissions: Tons,
    pub ch4_plant: Tons,
    pub ch4_sludge_storage_containers: Tons,
    pub ch4_sludge_bags: Tons,
    pub ch4_water: Tons,
    pub ch4_combined_heat_and_power_plant: Tons,
    pub ch4_emissions: Tons,
    pub fossil_emissions: Tons,
    pub fecl3: Tons,
    pub feclso4: Tons,
    pub caoh2: Tons,
    pub synthetic_polymers: Tons,
    pub electricity_mix: Tons,
    pub oil_emissions: Tons,
    pub gas_emissions: Tons,
    pub operating_materials: Tons,
    pub sewage_sludge_transport: Tons,
    pub total_emissions: Tons,
    pub direct_emissions: Tons,
    pub process_energy_savings: Tons,
    pub photovoltaic_expansion_savings: Tons,
    pub wind_expansion_savings: Tons,
    pub water_expansion_savings: Tons,
    pub district_heating_savings: Tons,
    pub fossil_energy_savings: Tons,
    pub indirect_emissions: Tons,
    pub other_indirect_emissions: Tons,
    pub excess_energy_co2_equivalent: Tons,
}
