[package]
name = "klick-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
# Project dependencies
klick-application = "=0.0.0"
klick-boundary = "=0.0.0"
klick-db-sqlite = "=0.0.0"
klick-domain = "=0.0.0"
klick-svg-charts = "=0.0.0"

# External dependencies
anyhow = "1.0.79"
axum = "0.7.3"
axum-extra = { version = "0.9.1", features = ["typed-header"] }
headers = "0.4.0"
log = "0.4.20"
mime_guess = "2.0.4"
parking_lot = "0.12.1"
rust-embed = { version = "8.2.0", features = ["axum"] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["net"] }
tower-http = { version = "0.5.0", features = ["cors"] }
uuid = { version = "1.6.1", features = ["v4"] }

[lints]
workspace = true
