[package]
name = "klick-application"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
klick-domain = "=0.0.0"

anyhow = "1.0.79"
log = "0.4.20"
thiserror = "1.0.56"
time = "0.3.32"

[lints]
workspace = true
