[package]
name = "klick-app-api"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
klick-boundary = "=0.0.0"

gloo-net = { version = "0.5.0", default-features = false, features = ["http", "json"] }
log = "0.4.20"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"

[lints]
workspace = true
