[package]
name = "klick-domain"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
bs58 = "0.5.0"
mailparse = "0.14.1"
pwhash = "1.0.0"
thiserror = "1.0.56"
time = "0.3.31"
uuid = { version = "1.7.0", features = ["v4"] }

[lints]
workspace = true
