[package]
name = "klick-domain"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
mailparse = "0.14.0"
pwhash = "1.0.0"
thiserror = "1.0.56"

[lints]
workspace = true
