[package]
name = "klick-domain"
description.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bs58 = "0.5.1"
derive_more = "0.99.17"
mailparse = "0.15.0"
pwhash = "1.0.0"
serde = { version = "1.0.202", features = ["derive"] }
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.60"
time = "0.3.36"
uuid = { version = "1.8.0", features = ["v4"] }

[lints]
workspace = true
