[package]
name = "klick-app-components"
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
klick-presenter = "=0.0.0"

Inflector = { version =  "0.11.4", default-features = false }
leptos = { version = "0.6.5", features = ["csr"] }
log = "0.4.20"

[lints]
workspace = true
