[package]
name = "klick-boundary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.79"
derive_more = "0.99.17"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.56"
uuid = { version = "1.6.1", features = ["serde"] }

[dependencies.klick-domain]
version = "=0.0.0"
optional = true

[dev-dependencies]
klick-boundary = { version = "=0.0.0", features = ["extra-derive", "conversion"] }
klick-domain = "=0.0.0"
uuid = { version = "1.6.1", features = ["v4"] }

[features]
conversion = ["dep:klick-domain"]
extra-derive = []

[lints]
workspace = true
