[package]
name = "klick-boundary"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.82"
derive_more = "0.99.17"
http = "1.1.0"
http-serde = "2.1.0"
log = "0.4.21"
num-derive = "0.4.2"
num-traits = { version = "0.2.18", default-features = false }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.116"
thiserror = "1.0.58"
time = { version = "0.3.36", features = ["serde"] }
uuid = { version = "1.8.0", features = ["serde"] }

[dependencies.klick-domain]
path = "../domain"

[dependencies.axum]
version = "0.7.5"
default-features = false
features = ["json"]
optional = true

[dev-dependencies]
klick-boundary = { version = "=0.0.0", features = ["extra-derive", "conversion"] }

uuid = { version = "1.8.0", features = ["v4"] }

[features]
conversion = []
extra-derive = []
axum = ["dep:axum"]

[lints]
workspace = true
